### PR TITLE
feat(validator): invoke chainsaw binary for health checks and add gpu-operator pod health check

### PR DESCRIPTION
**Pull request by xdu31**
## Summary

- Invoke chainsaw binary for health checks instead of importing the Go library runner (which fails to compile with Go 1.26 due to missing `ModulePath()` on `TestDeps`)
- Add gpu-operator pod health check using chainsaw `error` operations — asserts no pods in Pending/Failed/Unknown phase in the `gpu-operator` namespace
- Rename `assert.yaml` → `health-check.yaml` to reflect the new Chainsaw Test format
- Add SHA256 checksum verification for chainsaw binary in Dockerfile and CI

## Why binary instead of Go library

Chainsaw v0.2.14's `pkg/runner` cannot compile with Go 1.26:

```
*internal.TestDeps does not implement "testing".testDeps (missing method ModulePath)
```

The vendored library only provides types + assertion engine (`checks.Check()`). The execution layer (`pkg/runner/`, `pkg/engine/operations/`) is not vendored because it fails to build. Building a custom executor would reimplement ~70% of chainsaw. The binary gives 100% compatibility with zero custom code.

## Architecture

```
Health check YAML format detection:
  isChainsawTest(yaml) ?
    YES → runChainsawBinary() → write to tmpdir → exec chainsaw test --test-dir <dir>
    NO  → assertRawResources() → Go library checks.Check() [existing path, unchanged]
```

Two code paths coexist: Chainsaw Test format (binary) and raw K8s resource YAML (Go library). Backward compatible — existing raw YAML assertions still use the Go library.

## Files changed

| File | Change |
|------|--------|
| `Dockerfile.validator` | Download chainsaw binary in builder stage with SHA256 checksum, COPY to final image |
| `.github/actions/setup-build-tools/action.yml` | Add SHA256 checksum verification to chainsaw install |
| `pkg/validator/chainsaw/binary.go` | **NEW**: `ChainsawBinary` interface + `chainsawBinary` exec implementation |
| `pkg/validator/chainsaw/runner.go` | Format detection (`isChainsawTest`), `runChainsawBinary`, `RunOption`/`WithChainsawBinary` |
| `pkg/validator/chainsaw/runner_test.go` | 8 new tests: format detection, binary pass/fail/error, file verification, backward compat |
| `pkg/validator/checks/deployment/expected_resources_check.go` | Pass `WithChainsawBinary()` to `chainsaw.Run()` |
| `recipes/checks/gpu-operator/health-check.yaml` | **NEW** (replaces `assert.yaml`): Chainsaw Test with `error` operations for pod health |
| `recipes/registry.yaml` | Update `assertFile` reference |
| `pkg/validator/resource_discovery_test.go` | Update `assert.yaml` → `health-check.yaml` references |
| `tests/e2e/run.sh` | Update references |
| `tests/chainsaw/cli/validate-chainsaw-healthcheck/chainsaw-test.yaml` | Update references |

## Test plan

- [ ] `go test -race ./pkg/validator/chainsaw/...` — unit tests for binary invocation + format detection
- [ ] `make test` — all packages pass
- [ ] `make lint` — no new lint issues
- [ ] Docker build: `docker build -f Dockerfile.validator -t test . && docker run --rm test chainsaw version`
- [ ] E2E: deploy validator Job with `--phase deployment`, verify chainsaw output in Job logs

### CODE REVIEW

**Review by lockwobr — DISMISSED** [review]

**Review by mchmarny — COMMENTED** [review]
Nice work overall — clean interface design, good test coverage, and the binary approach is pragmatic given the Go 1.26 compatibility issue. The dual code path preserves backward compat well.

The timeout mismatch (ChainsawAssertTimeout=2m vs health-check.yaml assert=5m) is the main thing to fix before merge. The other comments are suggestions/nits that could be follow-ups.

**Review by yuanchen8911 — APPROVED** [review]
/lgtm
